title: CRC-SC Help Center
description: Microsoft 365 documentation for CRC-SC board members
baseurl: /crc-sc-help
url: https://yarmand.github.io

remote_theme: just-the-docs/just-the-docs@v0.10.0

# Enable search
search_enabled: true
search.heading_level: 3

# Aux links (top-right)
aux_links:
  "View on GitHub":
    - "https://github.com/yarmand/crc-sc-help"

# Footer
footer_content: "CRC-SC Help Center &mdash; Helping board members get the most out of Microsoft 365."

# Color scheme
color_scheme: light

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Plugins
plugins:
  - jekyll-remote-theme
